// ============================================================
// Studio OS — Mock Data for Development
// ============================================================

import type { Project, Task, DashboardStats } from '@/types';

export const mockData = {
  stats: {
    totalProjects: 12,
    activeTasks: 47,
    completedTasks: 156,
    teamMembers: 8,
  } satisfies DashboardStats,

  projects: [
    {
      id: 'p1',
      name: 'Brand Redesign',
      description: 'Complete brand overhaul including logo, typography, and color system',
      status: 'active',
      color: '#8b5cf6',
      memberCount: 5,
      taskCount: 24,
      completedTaskCount: 18,
      createdAt: new Date('2025-01-15'),
      updatedAt: new Date('2025-07-10'),
    },
    {
      id: 'p2',
      name: 'Mobile App v2',
      description: 'Next generation mobile application with enhanced UX',
      status: 'active',
      color: '#06b6d4',
      memberCount: 8,
      taskCount: 42,
      completedTaskCount: 28,
      createdAt: new Date('2025-03-01'),
      updatedAt: new Date('2025-07-12'),
    },
    {
      id: 'p3',
      name: 'Marketing Campaign',
      description: 'Q3 integrated marketing campaign across all channels',
      status: 'active',
      color: '#f43f5e',
      memberCount: 4,
      taskCount: 16,
      completedTaskCount: 7,
      createdAt: new Date('2025-05-20'),
      updatedAt: new Date('2025-07-14'),
    },
    {
      id: 'p4',
      name: 'Design System',
      description: 'Unified component library and design tokens',
      status: 'active',
      color: '#22c55e',
      memberCount: 3,
      taskCount: 31,
      completedTaskCount: 25,
      createdAt: new Date('2025-02-10'),
      updatedAt: new Date('2025-07-08'),
    },
    {
      id: 'p5',
      name: 'API Integration',
      description: 'Third-party API integrations and webhook system',
      status: 'draft',
      color: '#f59e0b',
      memberCount: 2,
      taskCount: 12,
      completedTaskCount: 0,
      createdAt: new Date('2025-07-01'),
      updatedAt: new Date('2025-07-01'),
    },
    {
      id: 'p6',
      name: 'Analytics Dashboard',
      description: 'Real-time analytics and reporting platform',
      status: 'archived',
      color: '#6366f1',
      memberCount: 6,
      taskCount: 38,
      completedTaskCount: 38,
      createdAt: new Date('2024-11-01'),
      updatedAt: new Date('2025-06-30'),
    },
  ] satisfies Project[],

  tasks: [
    {
      id: 't1',
      title: 'Update color palette tokens',
      description: 'Revise the design token system with new brand colors',
      status: 'in-progress',
      priority: 'high',
      projectId: 'p1',
      assigneeId: 'u1',
      tags: ['design', 'tokens'],
      dueDate: new Date('2025-07-20'),
      createdAt: new Date('2025-07-01'),
      updatedAt: new Date('2025-07-14'),
    },
    {
      id: 't2',
      title: 'Implement auth flow',
      description: 'Set up authentication with OAuth2 and session management',
      status: 'todo',
      priority: 'urgent',
      projectId: 'p2',
      assigneeId: 'u2',
      tags: ['backend', 'security'],
      dueDate: new Date('2025-07-18'),
      createdAt: new Date('2025-07-05'),
      updatedAt: new Date('2025-07-05'),
    },
    {
      id: 't3',
      title: 'Create social media assets',
      description: 'Design banner images for all social platforms',
      status: 'review',
      priority: 'medium',
      projectId: 'p3',
      tags: ['design', 'social'],
      dueDate: new Date('2025-07-22'),
      createdAt: new Date('2025-07-08'),
      updatedAt: new Date('2025-07-13'),
    },
    {
      id: 't4',
      title: 'Button component variants',
      description: 'Add ghost, outline, and destructive button variants',
      status: 'done',
      priority: 'medium',
      projectId: 'p4',
      assigneeId: 'u1',
      tags: ['components', 'ui'],
      createdAt: new Date('2025-06-15'),
      updatedAt: new Date('2025-07-10'),
    },
    {
      id: 't5',
      title: 'Performance audit',
      description: 'Run Lighthouse and optimize critical rendering path',
      status: 'todo',
      priority: 'high',
      projectId: 'p2',
      tags: ['performance'],
      dueDate: new Date('2025-07-25'),
      createdAt: new Date('2025-07-12'),
      updatedAt: new Date('2025-07-12'),
    },
    {
      id: 't6',
      title: 'Write API documentation',
      description: 'Document all REST endpoints with examples',
      status: 'todo',
      priority: 'low',
      projectId: 'p5',
      tags: ['docs'],
      dueDate: new Date('2025-08-01'),
      createdAt: new Date('2025-07-14'),
      updatedAt: new Date('2025-07-14'),
    },
    {
      id: 't7',
      title: 'Navigation redesign',
      description: 'Redesign main navigation with mega menu support',
      status: 'in-progress',
      priority: 'high',
      projectId: 'p1',
      assigneeId: 'u3',
      tags: ['design', 'ux'],
      dueDate: new Date('2025-07-19'),
      createdAt: new Date('2025-07-03'),
      updatedAt: new Date('2025-07-15'),
    },
    {
      id: 't8',
      title: 'Set up CI/CD pipeline',
      description: 'Configure GitHub Actions for automated testing and deployment',
      status: 'done',
      priority: 'urgent',
      projectId: 'p2',
      assigneeId: 'u2',
      tags: ['devops'],
      createdAt: new Date('2025-06-20'),
      updatedAt: new Date('2025-07-01'),
    },
  ] satisfies Task[],

  recentActivity: [
    { id: 'a1', action: 'completed', target: 'Button component variants', user: 'Sarah Chen', time: '2 hours ago' },
    { id: 'a2', action: 'commented on', target: 'Navigation redesign', user: 'Alex Rivera', time: '4 hours ago' },
    { id: 'a3', action: 'created', target: 'Performance audit', user: 'Jordan Kim', time: '6 hours ago' },
    { id: 'a4', action: 'moved', target: 'Create social media assets', user: 'Morgan Blake', time: '8 hours ago' },
    { id: 'a5', action: 'assigned', target: 'Implement auth flow', user: 'Sarah Chen', time: '1 day ago' },
  ],
};
